services:
  consul:
    image: hashicorp/consul:1.19
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500"]
    ports:
      - "8500:8500"
  container-to-consul:
    build: ./
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      consul:
        condition: service_healthy
    environment:
      c2c_consul__host: consul