name: CI
on:
    push:
      branches: ["*"]
    pull_request:
      branches: [main]

jobs:
    run-unit-tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '18'
        - name: Install dependencies
          run: npm install
        - name: Run tests
          run: npm test
    run-e2e-tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Run e2e tests
          uses: hoverkraft-tech/compose-action@v2.0.1
          with:
            compose-file: docker-compose-e2e.yaml
            up-flags: --build --force-recreate --abort-on-container-exit --exit-code-from playwright
            